[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.21"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["InfoPilotSmartAccount", "InfoPilotFactory"]
fs_permissions = [{ access = "read-write", path = "./deployments" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# RPC endpoints
[rpc_endpoints]
coston2 = "https://coston2.enosys.global/ext/C/rpc"
coston2_alt = "https://coston2-api.flare.network/ext/C/rpc"

# Etherscan (Flarescan) configuration
[etherscan]
# coston2 = { key = "${FLARESCAN_API_KEY}", url = "https://api.etherscan.io/v2/api" }
coston2 = { key = "", url = "https://coston2-explorer.flare.network/api" }

